
eventIds: 0dc58e03-4864-4cdb-8cf9-c5c1d01949fc, 55f8c3f0-c606-41ac-ad30-6ec22a5b8e6f, 722efd8f-f06c-49c3-b88c-90c3b43c8489, b92cb406-6fbc-45e9-b220-4b9bbc9b9f43, 494345a0-dc42-4323-9452-b922e211a56c

server:
  port: 8081

logging.level:
  org.apache.kafka: WARN
  org.springframework.cloud.stream: INFO
  io.pivotal.dfrey: DEBUG

spring:

  jackson:
    serialization:
      write_dates_as_timestamps: false

  cloud:
    stream:
      bindings:
        scst-events-output:
          destination: scst-events
          contentType: application/json
        scst-events-input:
          destination: scst-events
          group: scst-events-stream
          contentType: application/json
          consumer:
            headerMode: raw
      kafka:
        streams:
          binder:
            configuration:
              commit.interval.ms: 1000
          bindings:
            scst-events-input:
              consumer.application-id: scst-demo
            scst-events-by-id:
              consumer:
                materializedAs: scst-events-by-id
